version: "3.9"

services:
  web:
    build: ./web
    container_name: desafio3_web
    depends_on:
      - db
      - cache
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASS=senha
      - DB_NAME=appdb

  db:
    image: postgres:15
    container_name: desafio3_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:7
    container_name: desafio3_cache

volumes:
  postgres_data:
