version: "3.9"

services:
  service_a:
    build: ./service_a
    container_name: desafio4_service_a
    ports:
      - "8001:8001"
    networks:
      - desafio4_rede

  service_b:
    build: ./service_b
    container_name: desafio4_service_b
    ports:
      - "8002:8002"
    depends_on:
      - service_a
    networks:
      - desafio4_rede

networks:
  desafio4_rede:
    driver: bridge